declare const _default: {};
export default _default;
export type Cli = import("./cli.js").Cli;
export type Packages = import("./PckgJson.js").Packages;
export type NpmOptions = object;
export type Result = {
    mode: string;
    package: string;
    range: string;
    _range: string;
    ignore?: boolean;
    wildcard?: string;
    latest?: string;
    max?: string;
    major?: string;
    minor?: string;
    patch?: string;
    final?: string;
    versions?: string[];
    error?: Error;
};
